apiVersion: v1
kind: Pod
spec:
  containers:
    - name: node
      image: mcr.microsoft.com/playwright:v1.58.2-noble
      command:
        - sleep
      args:
        - infinity
      env:
        - name: PLAYWRIGHT_BROWSERS_PATH
          value: "/ms-playwright"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"