apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-front
  namespace: the-tip-top-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-front
  template:
    metadata:
      labels:
        app: nuxt-front
    spec:
      containers:
        - name: web
          image: joanisky/the-tip-top-front:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nuxt-front-config

          # Variables sensibles depuis Secret (créé par Jenkins)
          env:
            - name: NUXT_SESSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nuxt-front-secrets
                  key: NUXT_SESSION_PASSWORD
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10